;Music defines
def MUSA_CNT			equ $05

def MUS_EMPTY			equ $00
def MUS_TITLE			equ $01
def MUS_GRAVEYARD		equ $02
def MUS_SWEETSHOP		equ $03
def MUS_SUBWAY			equ $04

def MUSB_CNT			equ $0A

def MUS_SCIFI			equ $01
def MUS_DESOLATION		equ $02
def MUS_LABORATORY		equ $03
def MUS_HAPPINESS		equ $04
def MUS_BEDROOM			equ $05
def MUS_BOSS1			equ $06
def MUS_BOSS2			equ $07
def MUS_BOSS3			equ $08
def MUS_BOSS4			equ $09

def MUSC_CNT			equ $06

def MUS_GARDEN			equ $01
def MUS_LVL_100_COMP	equ $02
def MUS_GAME_100_COMP	equ $03
def MUS_GAME_OVER		equ $04
def MUS_CITY			equ $05

;SFX defines
def SFX_CNT				equ $3C

def SFX_MENU_SELECT		equ $00
def SFX_MENU_CONFIRM	equ $01
def SFX_PSW_ACCEPTED	equ $02
def SFX_PSW_REJECTED	equ $03
def SFX_EXTRA_HEALTH	equ $04
def SFX_ROCKET_PICKUP	equ $05
def SFX_ROCKET_EXPLODE	equ $06
def SFX_ROCKET_SHOOT	equ $07
def SFX_ROCKET_LOW_FUEL	equ $08
def SFX_JUMP			equ $09
def SFX_LAND			equ $0A
def SFX_SNOTT			equ $0B
def SFX_SWITCH1			equ $0C
def SFX_SWITCH2			equ $0D
def SFX_DOUBLE_JUMP		equ $0E
def SFX_COIN1			equ $0F
def SFX_COIN2			equ $10
def SFX_SELECT_WEAPON	equ $11
def SFX_EXTRA_LIFE		equ $12
def SFX_TOILET_PORTAL	equ $13
def SFX_SNOTT_BOUNCE	equ $14
def SFX_DOOR_SHUT		equ $15
def SFX_ENEMY_HIT		equ $16
def SFX_PORTAL_LOCKED1	equ $17
def SFX_PORTAL_LOCKED2	equ $18
def SFX_ALARM			equ $19
def SFX_DO_NOT_USE		equ $1A
def SFX_BOSS_DEFEATED	equ $1B
def SFX_CANNON1			equ $1C
def SFX_CANNON2			equ $1D
def SFX_ASTEROID		equ $1E
def SFX_DOOR_OPEN		equ $1F
def SFX_CANNON3			equ $20
def SFX_SLIDE			equ $21
def SFX_PICKUP1			equ $22
def SFX_PICKUP2			equ $23
def SFX_PICKUP3			equ $24
def SFX_PICKUP4			equ $25
def SFX_TELEPORT		equ $26
def SFX_ENEMY_DIE		equ $27
def SFX_FALL_HOLE		equ $28
def SFX_GOT_ALL_COINS	equ $29
def SFX_GUN_FIRE1		equ $2A
def SFX_GUN_FIRE2		equ $2B
def SFX_GUN_FIRE3		equ $2C
def SFX_GUN_FIRE4		equ $2D
def SFX_JIM_DOWN		equ $2E
def SFX_JIM_HIT1		equ $2F
def SFX_JIM_HIT2		equ $30
def SFX_JIM_HIT3		equ $31
def SFX_BOSS_HIT1		equ $32
def SFX_RUMBLE			equ $33
def SFX_BOSS_HIT2		equ $34
def SFX_EVIL_JIM_ROCKET	equ $35
def SFX_BOSS_EXPLODE1	equ $36
def SFX_BOSS_EXPLODE2	equ $37
def SFX_SNAP1			equ $38
def SFX_SNAP2			equ $39
def SFX_BABY_FIRE		equ $3A
def SFX_EMPTY			equ $3B